---
swagger: "2.0"
info:
  description: "Take a deep look in the world of a malware samples"
  version: "0.1.0"
  title: "MalwareOWL"
host: "api.temporary.com"
basePath: "/v1"
schemes:
- "https"
produces:
- "application/json+ld"
paths:
  /:
    get:
      tags:
      - "Index"
      summary: "Index front"
      description: "The frontend with form for file"
      operationId: "indexGET"
      parameters: []
      responses:
        200:
          description: "html page"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Index"
  /sparql:
    get:
      tags:
      - "Sparql"
      summary: "Sparql endpoint"
      description: "The sparql endpoint offers the possibility to interogate our knowledge\
        \ graf based on Sparql queries.\n"
      operationId: "sparqlGET"
      parameters:
      - name: "query"
        in: "query"
        description: "Sparql query to process"
        required: true
        type: "string"
      responses:
        200:
          description: "A json+ld collection of RDF triples"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Queryresult"
        204:
          description: "No content"
          schema:
            $ref: "#/definitions/Error"
        206:
          description: "Partial content - query to big."
        400:
          description: "Bad request - incorect sparql query"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Sparql"
  /process/file:
    post:
      summary: "File submission"
      description: "Endpoint for submitting files for analysis."
      operationId: "processFilePOST"
      parameters:
      - name: "file"
        in: "formData"
        description: "The file to be submitted."
        required: false
        type: "file"
      - name: "email"
        in: "formData"
        description: "Email to be accesed upon completion."
        required: false
        type: "string"
      responses:
        201:
          description: "File was succesfully submited."
        304:
          description: "Not modified - file already processed."
        400:
          description: "Error at processing the file."
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Default"
  /process/hash:
    post:
      tags:
      - "Submission"
      summary: "Hash submission"
      description: "Endpoint for requesting hash analysis."
      operationId: "processHashPOST"
      parameters:
      - name: "hash"
        in: "formData"
        description: "The hash to be analysed."
        required: false
        type: "string"
      - name: "email"
        in: "formData"
        description: "Email to be accesed upon completion."
        required: false
        type: "string"
      responses:
        201:
          description: "Hash was succesfully submited."
        304:
          description: "Not modified - file already processed."
        400:
          description: "Error at processing the hash."
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Submission"
  /sim/{hash}/{procentage}/{sequence}:
    get:
      tags:
      - "Similarity"
      summary: "Similarity endpoint"
      description: "Computes various similarity properties for a hash and a certain\
        \ property level."
      operationId: "simHashProcentageSequenceGET"
      parameters:
      - name: "hash"
        in: "path"
        description: "The target hash."
        required: true
        type: "string"
      - name: "procentage"
        in: "path"
        description: "The similarity procentage to be used in the query."
        required: true
        type: "integer"
      - name: "sequence"
        in: "path"
        description: "The level sequence."
        required: true
        type: "string"
      responses:
        200:
          description: "Request all good."
          schema:
            $ref: "#/definitions/Similarityresult"
        204:
          description: "No content."
        206:
          description: "Partial content."
        400:
          description: "Bad request. Error at processing the similarity request."
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Not found."
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error."
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Similarity"
  /value/hash/{hash}/{sequence}:
    get:
      tags:
      - "Value"
      summary: "Value endpoint"
      description: "Retrives the value of a certain property for a certain hash."
      operationId: "valueHashHashSequenceGET"
      parameters:
      - name: "hash"
        in: "path"
        description: "The target hash."
        required: true
        type: "string"
      - name: "sequence"
        in: "path"
        description: "The level sequence."
        required: true
        type: "string"
      responses:
        200:
          description: "Request all good."
          schema:
            $ref: "#/definitions/Valueresult"
        204:
          description: "No content."
        206:
          description: "Partial content."
        400:
          description: "Bad request. Error at processing the value request."
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Not found."
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error."
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Value"
  /value/sim/{value}/{sequence}:
    get:
      tags:
      - "Similarity"
      - "Value"
      summary: "Value similarity endpoint"
      description: "Retrives the entities related to the value."
      operationId: "valueSimValueSequenceGET"
      parameters:
      - name: "value"
        in: "path"
        description: "The target hash."
        required: true
        type: "string"
      - name: "sequence"
        in: "path"
        description: "The level sequence."
        required: true
        type: "string"
      responses:
        200:
          description: "Request all good."
          schema:
            $ref: "#/definitions/ValueSymresult"
        204:
          description: "No content."
        206:
          description: "Partial content."
        400:
          description: "Bad request. Error at processing the value request."
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Not found."
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Similarity"
  /multisym/{hash}:
    get:
      tags:
      - "Similarity"
      summary: "Hash multivalue similarity endpoint"
      description: "Retrives the similar entities which related to the current target\
        \ via multiple specified values."
      operationId: "multisymHashGET"
      parameters:
      - name: "hash"
        in: "path"
        description: "The target hash."
        required: true
        type: "string"
      - in: "body"
        name: "sequences"
        description: "The level sequence."
        required: true
        schema:
          $ref: "#/definitions/sequences"
      responses:
        200:
          description: "Request all good."
          schema:
            $ref: "#/definitions/Similarityresult"
        204:
          description: "No content."
        206:
          description: "Partial content."
        400:
          description: "Bad request. Error at processing the value request."
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Not found."
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Similarity"
  /status/{hash}:
    get:
      tags:
      - "Status"
      summary: "Hash status"
      description: "Interogate the processing status of a hash."
      operationId: "statusHashGET"
      parameters:
      - name: "hash"
        in: "path"
        description: "The target hash."
        required: true
        type: "string"
      responses:
        200:
          description: "Done."
          schema:
            $ref: "#/definitions/StatusResponse"
        204:
          description: "No content."
        400:
          description: "Bad request. Invalid hash."
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Not found. Hash not found."
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error."
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Status"
definitions:
  StatusResponse:
    type: "object"
    properties:
      status:
        type: "string"
        description: "Status of the file."
      timestamp:
        type: "integer"
        description: "Timestamp of the result"
  Queryresult:
    type: "object"
    properties:
      result:
        type: "object"
        description: "The object containing the result of the query"
        properties: {}
      timestamp:
        type: "integer"
        description: "Timestamp of the result"
  Similarityresult:
    type: "object"
    properties:
      hash_array:
        type: "array"
        description: "An array of files that match a certain procentage of similarity"
        items:
          $ref: "#/definitions/Similarityresult_hash_array"
  Valueresult:
    type: "object"
    properties:
      values:
        type: "array"
        description: "An array of URL's towards specific properties values describing\
          \ the level sequence specified."
        items:
          type: "string"
  ValueSymresult:
    type: "object"
    properties:
      entities:
        type: "array"
        description: "An array of URL's towards specific entities which directly relate\
          \ to the value."
        items:
          type: "string"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
  sequences:
    required:
    - "values"
    properties:
      values:
        type: "array"
        items:
          type: "string"
  Similarityresult_hash_array:
    properties:
      url:
        type: "string"
        description: "The url to the interogation for that particular hash."
      procentage:
        type: "integer"
        description: "The procentage of similarity with the original hash."
    description: "An object entry"
